version: "3.8"
services:
  graph:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TARGETPLATFORM=linux/arm64
    platform: linux/arm64
    container_name: graphiti
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - PORT=8000
      - MODEL_NAME=gemini-1.5-flash
      - API_PASSWORD=${API_PASSWORD}
    networks:
      - graphiti-net
  neo4j:
    image: neo4j:2025.04.0
    platform: linux/arm64
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_server_config_strict_validation_enabled=false
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "http://localhost:7474"]
      interval: 10s
      timeout: 15s
      retries: 20
      start_period: 180s
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2.5G
    networks:
      - graphiti-net
volumes:
  neo4j_data:
  neo4j_logs:
networks:
  graphiti-net:
    driver: bridge
